### ISSUE TITLE
Ppoblem with compilation after updating serde to v1.0.62

### ISSUE THREAD

**Issue by MaxGraey** [cesarb/blake2-rfc#10]
Hi, need help. After updating serde I catch a lot of errors addressed to i128/u128 types.

```rust
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.62/src/de/value.rs:242:29
    |
242 |     primitive_deserializer!(i128, "an `i128`.", I128Deserializer, visit_i128);
    |                             ^^^^
    |
    = help: add #![feature(i128_type)] to the crate attributes to enable

If you want more information on this error, try using "rustc --explain E0658"
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.62/src/de/value.rs:243:29
    |
243 |     primitive_deserializer!(u128, "a `u128`.", U128Deserializer, visit_u128);
    |                             ^^^^
    |
    = help: add #![feature(i128_type)] to the crate attributes to enable

```

**Comment by cesarb** [comment]
This is the wrong repository, serde is at https://github.com/serde-rs/serde, but I can answer your question: Rust 1.26 has stabilized `i128` and `u128` (https://blog.rust-lang.org/2018/05/10/Rust-1.26.html), and serde 1.0.62 added support for both (https://github.com/serde-rs/serde/releases/tag/v1.0.62), so you need to upgrade Rust to 1.26 or later, or downgrade serde to 1.0.61 or earlier.

**Comment by MaxGraey** [comment]
Thanks. I already opened in serde repo.

**PS** I have got Rust 1.27.0-beta.8 and 1.28.0-nightly.
